models/Operators.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "operators".
 *
 * @property int $id
 * @property string $name
 * @property string $surname
 * @property string $email
 * @property string $birth_date
 * @property int $status_id
 * @property string $tel1
 * @property string $tel2
 * @property string $tel3
 * @property string $created_at
 */
class Operators extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'operators';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status_id'], 'integer'],
            [['created_at'], 'safe'],
            [['name', 'surname', 'email'], 'string', 'max' => 50],
            [['birth_date'], 'string', 'max' => 12],
            [['tel1', 'tel2', 'tel3'], 'string', 'max' => 20],
            [['name', 'surname', 'email', 'status_id'], 'required'],
            ['email', 'email'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Ім\'я оператора',
            'surname' => 'Прізвище оператора',
            'birth_date' => 'Дата народження (у форматі РРРР-ММ-ДД)',
            'email' => 'Email',
            'status_id' => 'Status ID',
            'tel1' => 'Придбаний номер телефону',
            'tel2' => 'Tel2',
            'tel3' => 'Tel3',
            'created_at' => 'Created At',
        ];
    }
}

controllers/OperatorsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Operators;
use app\models\OperatorsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use Twilio\Rest\Client;

/**
 * OperatorsController implements the CRUD actions for Operators model.
 */
class OperatorsController extends Controller
{
    const SID = ''; // Тут вказується SID аккаунта Twilio
    const TOKEN = ''; // Тут вказується Authtoken аккаунта Twilio

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Operators models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OperatorsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    /* Отримання списку доступиних номерів */
    public function actionLists($id)
    {
        $sid    = self::SID;
        $token  = self::TOKEN;
        $twilio = new Client($sid, $token);

        $mobile = $twilio->availablePhoneNumbers($id)
                 ->mobile
                 ->read(array(), 20);

        $phonesArray = [];

        foreach ($mobile as $record) {
            $arr_tmp = [];
            $arr_tmp['friendly_name'] = $record->friendlyName. ' '. '('. $record->isoCountry. ')';
            $arr_tmp['number'] = $record->phoneNumber;
            $phonesArray[] = $arr_tmp;
        }
        
        if (!empty($phonesArray)) {
            echo "<option value=''>Виберіть номер після вибору країни</option>";
            foreach ($phonesArray as $phone) {
                echo "<option value='". $phone['number']. "'>".$phone['friendly_name']."</option>";
            }
        } else {
            echo "<option>------</option>";
        }        
    }

    /* Купівля обраного номера */
    public function actionBuy($n) 
    {
        $sid    = self::SID;
        $token  = self::TOKEN;
        $twilio = new Client($sid, $token);

        $incoming_phone_number = $twilio->incomingPhoneNumbers
            ->create(array("phoneNumber" => $n)
        );

        print($incoming_phone_number->phoneNumber);
    }

    /**
     * Displays a single Operators model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Operators model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Operators();

        $sid    = self::SID;
        $token  = self::TOKEN;
        $twilio = new Client($sid, $token);

        // Отримання списку доступних країн

        $availablePhoneNumbers = $twilio->availablePhoneNumbers
                                ->read(array(), 200);
        $countriesArray = [];

        foreach ($availablePhoneNumbers as $record) {
            $arr_tmp = [];
            $arr_tmp['country_code'] = $record->countryCode;
            $arr_tmp['country'] = $record->country;
            $countriesArray[] = $arr_tmp;
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'countriesArray' => $countriesArray,
            'phonesArray' => []
        ]);
        echo $sid;
    }

    /**
     * Updates an existing Operators model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Operators model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Operators model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Operators the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Operators::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/operators/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Operators */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operators-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="form-group">
    <label for="countries_list">Тут ви можете придбати номер для оператора. Вкажіть країну для номера.</label>
    <?= Html::dropDownList('countries_list', null, ArrayHelper::map($countriesArray,'country_code','country'), ['prompt' => 'Вкажіть країну для придбання номера', 'class' => 'form-control', 
        'onchange' => '
            $.get("/operators/lists?id='.'"+$(this).val(), function(data) {
                $("select#phones_list").html(data);
            });
            ']); ?>
    </div>

    <div class="form-group">
    <label for="phones_list">Виберіть бажаний номер.</label>
    <?= Html::dropDownList('phones_list', null, ArrayHelper::map($phonesArray,'number','friendly_name'), ['prompt' => 'Виберіть номер після вибору країни', 'class' => 'form-control phones_list','id' => 'phones_list']); ?>
    <br>
    <?= Html::a('Придбати номер',['/operators/create'], ['class' => 'buy-number']);  ?>
    </div>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'birth_date')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status_id')->dropDownList(['1' => '1', '0' => '0']) ?>

    <?php     
        $this->registerJsFile("@web/js/script.js",[
            'depends' => [
                \yii\web\JqueryAsset::className()
            ]
        ]); 
    ?>

    <?= $form->field($model, 'tel1')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/operators/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OperatorsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="operators-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'birth_date') ?>

    <?= $form->field($model, 'status_id') ?>

    <?php // echo $form->field($model, 'tel1') ?>

    <?php // echo $form->field($model, 'tel2') ?>

    <?php // echo $form->field($model, 'tel3') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/operators/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Operators */

$this->title = 'Створити Оператора';
$this->params['breadcrumbs'][] = ['label' => 'Operators', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="operators-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'countriesArray' => $countriesArray,
        'phonesArray' => []
    ]) ?>

</div>

views/operators/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel app\models\OperatorsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Оператори';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="operators-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Додати Оператора', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            'surname',
            'birth_date',
            'status_id',
            'tel1',
            //'tel2',
            //'tel3',
            //'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

views/operators/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Operators */

$this->title = 'Редагувати Оператора: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Оператори', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="operators-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/operators/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Operators */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Оператори', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="operators-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'surname',
            'birth_date',
            'status_id',
            'tel1',
            'tel2',
            'tel3',
            'created_at',
        ],
    ]) ?>

</div>